name = "DeRham"
uuid = "0ea6bb9e-09b2-4dc0-b975-f97753fde228"
version = "0.1.0"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Debugger = "0.7.10"
