name = "DeRham"
uuid = "0ea6bb9e-09b2-4dc0-b975-f97753fde228"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
