name = "DeRham"
uuid = "0ea6bb9e-09b2-4dc0-b975-f97753fde228"
version = "0.1.0"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GPUFiniteFieldMatrices = "465031f1-b347-4f72-85f6-baf667cdf853"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LFUDACache = "4ae1174a-2808-43b3-975e-65e36c59b120"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[sources]
GPUFiniteFieldMatrices = {rev = "main", url = "https://github.com/UCSD-computational-number-theory/GPUFiniteFieldMatrices.jl.git"}

[compat]
CSV = "0.10.15"
CUDA = "5.7.3"
DataFrames = "1.7.0"
GPUFiniteFieldMatrices = "0.3.0"
# HTTP = "1.10.19"
JSON = "0.21.4"
LFUDACache = "0.1.1"
LRUCache = "1.6.2"
OhMyThreads = "0.8.3"
UnicodePlots = "3.8.1"
